"""
response.py
Data model for system responses in the Smart City Traffic AI System.
Defines the structure of outputs generated by the system.
"""


class SystemResponse:
    """
    Represents the final response generated by the Smart City Traffic AI System.
    
    This class aggregates outputs from various modules and formats them
    into a coherent, operationally meaningful response.
    
    Attributes:
        request_id (str): ID of the request this response belongs to
        request_category (str): Category of the original request
        status (str): Overall status (Approved, Rejected, Pending)
        modules_used (list): List of modules that processed this request
    """
    
    def __init__(self, request_id, request_category):
        """
        Initialize a SystemResponse.
        
        Args:
            request_id (str): ID of the original request
            request_category (str): Category of the original request
        """
        self.request_id = request_id
        self.request_category = request_category
        self.status = "Pending"
        self.modules_used = []
        
        # Module-specific outputs (populated selectively)
        self.recommended_route = None
        self.estimated_travel_time = None
        self.estimated_cost = None
        self.predicted_priority = None
        self.policy_status = None
        self.policy_reason = None
        self.control_action = None
        self.decision_message = None
        self.explanatory_text = None
    
    def add_module_usage(self, module_name):
        """
        Record that a module was used in processing this request.
        
        Args:
            module_name (str): Name of the module used
        """
        if module_name not in self.modules_used:
            self.modules_used.append(module_name)
    
    def set_route_info(self, route, travel_time, cost=None):
        """
        Set route information from Search module.
        
        Args:
            route (list): List of locations forming the route
            travel_time (float): Estimated travel time
            cost (float, optional): Total route cost. Defaults to None.
        """
        self.recommended_route = route
        self.estimated_travel_time = travel_time
        if cost is not None:
            self.estimated_cost = cost
    
    def set_priority(self, priority_level):
        """
        Set predicted priority from ANN module.
        
        Args:
            priority_level (str): Predicted priority level
        """
        self.predicted_priority = priority_level
    
    def set_policy_result(self, status, reason=None):
        """
        Set policy validation result from Logic/KB module.
        
        Args:
            status (str): Policy status (Approved, Rejected)
            reason (str, optional): Explanation for the decision
        """
        self.policy_status = status
        self.policy_reason = reason
    
    def set_control_action(self, action):
        """
        Set control action from CSP module.
        
        Args:
            action (dict or str): Assigned control action/plan
        """
        self.control_action = action
    
    def set_final_decision(self, status, message):
        """
        Set the final decision and message.
        
        Args:
            status (str): Final status (Approved, Rejected)
            message (str): Decision message
        """
        self.status = status
        self.decision_message = message
    
    def to_dict(self):
        """
        Convert response to dictionary, including only relevant fields.
        
        Returns:
            dict: Dictionary with selectively included fields
        """
        result = {
            'request_id': self.request_id,
            'request_category': self.request_category,
            'status': self.status,
            'modules_used': self.modules_used
        }
        
        # Include fields only if they were populated
        if self.recommended_route is not None:
            result['recommended_route'] = self.recommended_route
            result['estimated_travel_time'] = self.estimated_travel_time
            if self.estimated_cost is not None:
                result['estimated_cost'] = self.estimated_cost
        
        if self.predicted_priority is not None:
            result['predicted_priority'] = self.predicted_priority
        
        if self.policy_status is not None:
            result['policy_status'] = self.policy_status
            if self.policy_reason:
                result['policy_reason'] = self.policy_reason
        
        if self.control_action is not None:
            result['control_action'] = self.control_action
        
        if self.decision_message is not None:
            result['decision_message'] = self.decision_message
        
        return result
    
    def __str__(self):
        """
        String representation of the response.
        
        Returns:
            str: Formatted response summary
        """
        lines = [
            f"=== System Response for Request {self.request_id} ===",
            f"Category: {self.request_category}",
            f"Status: {self.status}",
            f"Modules Used: {', '.join(self.modules_used)}"
        ]
        
        if self.predicted_priority:
            lines.append(f"Predicted Priority: {self.predicted_priority}")
        if self.policy_status:
            lines.append(f"Policy Status: {self.policy_status}")
        if self.recommended_route:
            lines.append(f"Route: {' -> '.join(self.recommended_route)}")
            lines.append(f"Estimated Time: {self.estimated_travel_time}")
        if self.control_action:
            lines.append(f"Control Action: {self.control_action}")
        if self.decision_message:
            lines.append(f"Decision: {self.decision_message}")
        
        return '\n'.join(lines)